#!/usr/bin/env python3
"""Run LSG-SLAM full pipeline on EuRoC V2_01_easy (align baseline vs Pocket).

Pipeline mirrors bash_scripts/run_euroc_sequence.bash + pose_graph_part_optim.py:
  1) Chunked frontend odometry (step=200, stride=5) via splatam.py
  2) loop_closure.py (find loops + segment re-runs)
  3) pose_graph_part_optim.py (pose-graph ATE + optional structure refine)

Usage:
  python run_lsg_pipeline_v2.py --mode both
  python run_lsg_pipeline_v2.py --mode baseline --skip_structure_refine
  python run_lsg_pipeline_v2.py --mode pocket --stage posegraph
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))


def load_base_config():
    spec = importlib.util.spec_from_file_location(
        "paper_full_v2", ROOT / "configs/euroc/paper_full_v2.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return dict(mod.config), mod


def write_chunk_config(workdir: str, scene: str, start: int, end: int, stride: int,
                       pocket_enable: bool, out_path: Path, base_cfg: dict, pocket_cfg: dict):
    cfg = dict(base_cfg)
    cfg["workdir"] = workdir
    cfg["run_name"] = f"{scene}_{start}_{end}_{stride}"
    cfg["scene_path"] = f"experiments/euroc/{cfg['run_name']}/params.npz"
    cfg["data"] = dict(cfg["data"])
    cfg["data"]["start"] = start
    cfg["data"]["end"] = end
    cfg["data"]["stride"] = stride
    cfg["data"]["sequence"] = scene
    cfg["data"]["basedir"] = f"euroc/{scene}/mav0/cam0"
    cfg["pocket_slam"] = dict(pocket_cfg)
    cfg["pocket_slam"]["enable"] = pocket_enable
    cfg["wandb"] = dict(cfg.get("wandb", {}))
    cfg["wandb"]["group"] = workdir
    cfg["wandb"]["name"] = cfg["run_name"]

    # Serialize as a loadable .py for splatam / loop_closure
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Auto-generated by run_lsg_pipeline_v2.py\n")
        f.write(f"config = {repr(cfg)}\n")
    return cfg


def run_cmd(cmd, env=None):
    print("\n>>>", " ".join(cmd), flush=True)
    t0 = time.time()
    env = dict(env or os.environ)
    # pose_graph / splatam imports need repo root on PYTHONPATH
    pp = env.get("PYTHONPATH", "")
    root = str(ROOT)
    env["PYTHONPATH"] = root if not pp else f"{root}:{pp}"
    subprocess.check_call(cmd, cwd=str(ROOT), env=env)
    print(f"<<< done in {time.time()-t0:.1f}s", flush=True)


def stage_chunks(label: str, workdir: str, pocket_enable: bool, scene: str,
                 full_start: int, full_end: int, stride: int, step: int,
                 base_cfg: dict, pocket_cfg: dict, gpu: str):
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu
    tmp_dir = ROOT / "configs/euroc/_gen" / label
    tmp_dir.mkdir(parents=True, exist_ok=True)

    for start in range(full_start, full_end, step):
        end = min(start + step, full_end)
        if start >= end:
            break
        run_name = f"{scene}_{start}_{end}_{stride}"
        params = ROOT / workdir / run_name / "params.npz"
        if params.exists():
            print(f"[skip chunk] {params}")
            continue
        cfg_path = tmp_dir / f"{run_name}.py"
        write_chunk_config(workdir, scene, start, end, stride, pocket_enable,
                           cfg_path, base_cfg, pocket_cfg)
        run_cmd([sys.executable, "scripts/splatam.py", str(cfg_path)], env=env)


def stage_loops(label: str, workdir: str, pocket_enable: bool, scene: str,
                full_start: int, full_end: int, stride: int,
                base_cfg: dict, pocket_cfg: dict, gpu: str):
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu
    tmp_dir = ROOT / "configs/euroc/_gen" / label
    tmp_dir.mkdir(parents=True, exist_ok=True)
    run_name = f"{scene}_{full_start}_{full_end}_{stride}"
    loops_dir = ROOT / workdir / f"{run_name}_loops"
    if (loops_dir / "found_loops.npy").exists():
        print(f"[skip loops] {loops_dir}")
        return
    cfg_path = tmp_dir / f"{run_name}_full_for_loops.py"
    write_chunk_config(workdir, scene, full_start, full_end, stride, pocket_enable,
                       cfg_path, base_cfg, pocket_cfg)
    run_cmd([sys.executable, "scripts/loop_closure.py", str(cfg_path)], env=env)


def stage_posegraph(workdir: str, scene: str, gpu: str, skip_structure_refine: bool,
                    structure_refine_iters: int):
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu
    cmd = [
        sys.executable, "tools/loop_closure/pose_graph_part_optim.py",
        "--base_folder", workdir,
        "--scene_name", scene,
        "--dataset_type", "euroc",
        "--structure_refine_iters", str(structure_refine_iters),
    ]
    if skip_structure_refine:
        cmd.append("--skip_structure_refine")
    run_cmd(cmd, env=env)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["baseline", "pocket", "both"], default="both")
    parser.add_argument("--stage", choices=["all", "chunks", "loops", "posegraph"], default="all")
    parser.add_argument("--gpu", default="0")
    parser.add_argument("--scene", default="V2_01_easy")
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--end", type=int, default=2200)
    parser.add_argument("--stride", type=int, default=5)
    parser.add_argument("--step", type=int, default=200)
    parser.add_argument("--skip_structure_refine", action="store_true",
                        help="Pose-graph ATE only (faster). Run again without flag for PSNR.")
    parser.add_argument("--structure_refine_iters", type=int, default=5000)
    args = parser.parse_args()

    base_cfg, mod = load_base_config()
    pocket_cfg = dict(base_cfg.get("pocket_slam", {}))

    jobs = []
    if args.mode in ("baseline", "both"):
        jobs.append(("baseline", "euroc_lsg_v2_baseline", False))
    if args.mode in ("pocket", "both"):
        jobs.append(("pocket", "euroc_lsg_v2_pocket", True))

    results_root = Path("/mnt/hdd/lls/pocket_slam_results/v2_lsg_pipeline")
    results_root.mkdir(parents=True, exist_ok=True)

    for label, workdir, pocket_enable in jobs:
        print(f"\n===== {label.upper()}  workdir={workdir}  pocket={pocket_enable} =====", flush=True)
        (ROOT / workdir).mkdir(parents=True, exist_ok=True)

        if args.stage in ("all", "chunks"):
            stage_chunks(label, workdir, pocket_enable, args.scene,
                         args.start, args.end, args.stride, args.step,
                         base_cfg, pocket_cfg, args.gpu)
        if args.stage in ("all", "loops"):
            stage_loops(label, workdir, pocket_enable, args.scene,
                        args.start, args.end, args.stride,
                        base_cfg, pocket_cfg, args.gpu)
        if args.stage in ("all", "posegraph"):
            stage_posegraph(workdir, args.scene, args.gpu,
                            args.skip_structure_refine, args.structure_refine_iters)

        # Collect ATE summary if present
        ate_path = ROOT / workdir / "PoseGraphResult" / "ate_summary.txt"
        if ate_path.exists():
            summary = ate_path.read_text()
            out = results_root / f"{label}_ate_summary.txt"
            out.write_text(summary)
            print(f"[{label}] ATE:\n{summary}")

    print("\nAll requested stages finished.")


if __name__ == "__main__":
    main()
